import { img1, img2, img3, img4, img5, img6 } from "../assets/images";

export const negotiableData = [
  {
    id: 1,
    name: "Smartphone X",
    description: "A flagship smartphone with cutting-edge technology.",
    price: "799.99",
    image: [img1, img2, img3, img4, img5],
    category: "Electronics",
    subCategory: ["Mobile Phones", "Smart Devices"],
    sizes: ["Standard"],
    date: "2024-12-01",
    rating: 4.8,
    bestseller: true,
  },
  {
    id: 2,
    name: "Gaming Laptop Z",
    description: "A high-performance laptop for gaming enthusiasts.",
    price: "1299.99",
    image: [img3, img5, img2, img1],
    category: "Computers",
    subCategory: ["Laptops", "Gaming"],
    sizes: ["15-inch", "17-inch"],
    date: "2024-11-20",
    rating: 4.7,
    bestseller: true,
  },
  {
    id: 3,
    name: "Wireless Earbuds",
    description: "Compact earbuds with superior sound quality.",
    price: "99.99",
    image: [img6, img4, img2, img1],
    category: "Audio",
    subCategory: ["Accessories", "Wearables"],
    sizes: ["One Size"],
    date: "2024-12-05",
    rating: 4.6,
    bestseller: false,
  },
  {
    id: 4,
    name: "Smartwatch Pro",
    description: "A feature-packed smartwatch for your daily needs.",
    price: "199.99",
    image: [img3, img5, img2, img1],
    category: "Wearables",
    subCategory: ["Watches", "Smart Devices"],
    sizes: ["Small", "Medium", "Large"],
    date: "2024-12-03",
    rating: 4.5,
    bestseller: true,
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    description: "Portable speaker with rich bass and long battery life.",
    price: "49.99",
    image: [img5, img2, img1, img1, img6],
    category: "Audio",
    subCategory: ["Speakers", "Accessories"],
    sizes: ["Standard"],
    date: "2024-12-06",
    rating: 4.4,
    bestseller: false,
  },
  {
    id: 6,
    name: "4K Television",
    description: "Ultra HD TV with vibrant picture quality.",
    price: "999.99",
    image: [img3, img3, img4, img1, img2],
    category: "Home Electronics",
    subCategory: ["Television", "Entertainment"],
    sizes: ["55-inch", "65-inch", "75-inch"],
    date: "2024-11-15",
    rating: 4.8,
    bestseller: true,
  },
  {
    id: 7,
    name: "Noise-Cancelling Headphones",
    description: "Experience immersive sound with noise cancellation.",
    price: "199.99",
    image: [img3, img5, img2, img1],
    category: "Audio",
    subCategory: ["Headphones", "Accessories"],
    sizes: ["One Size"],
    date: "2024-11-25",
    rating: 4.7,
    bestseller: true,
  },
  {
    id: 8,
    name: "Fitness Tracker",
    description: "Track your fitness goals with accuracy.",
    price: "49.99",
    image: [img5, img2, img1, img1, img6],
    category: "Wearables",
    subCategory: ["Health", "Accessories"],
    sizes: ["Small", "Medium", "Large"],
    date: "2024-12-02",
    rating: 4.3,
    bestseller: false,
  },
  {
    id: 9,
    name: "Gaming Console",
    description: "Next-gen gaming console for an immersive experience.",
    price: "499.99",
    image: [img3, img3, img4, img1, img2],
    category: "Gaming",
    subCategory: ["Consoles", "Entertainment"],
    sizes: ["Standard"],
    date: "2024-12-10",
    rating: 4.9,
    bestseller: true,
  },
  {
    id: 10,
    name: "Electric Scooter",
    description: "Eco-friendly scooter for urban commuting.",
    price: "299.99",
    image: [img5, img2, img1, img1, img6],
    category: "Transportation",
    subCategory: ["Electric Vehicles", "Commuting"],
    sizes: ["Standard"],
    date: "2024-11-30",
    rating: 4.6,
    bestseller: true,
  },
  {
    id: 11,
    name: "Drone X",
    description:
      "High-performance drone with a 4K camera for aerial photography.",
    price: "599.99",
    image: [img5, img4, img3, img2, img1],
    category: "Electronics",
    subCategory: ["Cameras", "Aerial Devices"],
    sizes: ["Standard"],
    date: "2024-12-12",
    rating: 4.7,
    bestseller: true,
  },
  {
    id: 12,
    name: "Digital Camera",
    description:
      "Compact digital camera with optical zoom and high resolution.",
    price: "299.99",
    image: [img3, img2, img6, img2, img5],
    category: "Photography",
    subCategory: ["Cameras", "Accessories"],
    sizes: ["Standard"],
    date: "2024-11-18",
    rating: 4.5,
    bestseller: false,
  },
  {
    id: 13,
    name: "Smart Refrigerator",
    description: "Revolutionize your kitchen with smart technology.",
    price: "1499.99",
    image: [img6, img2, img1, img4, img5],
    category: "Home Appliances",
    subCategory: ["Refrigerators", "Smart Home"],
    sizes: ["Standard"],
    date: "2024-12-04",
    rating: 4.9,
    bestseller: true,
  },
  {
    id: 14,
    name: "Electric Kettle",
    description: "Fast-boil electric kettle with a sleek design.",
    price: "49.99",
    image: [img4, img2, img2, img4, img6],
    category: "Kitchen Appliances",
    subCategory: ["Kettles", "Home Essentials"],
    sizes: ["One Size"],
    date: "2024-11-22",
    rating: 4.4,
    bestseller: false,
  },
  {
    id: 15,
    name: "Air Purifier",
    description: "Breathe fresh air with advanced purification technology.",
    price: "199.99",
    image: [img5, img2, img2, img4, img6],
    category: "Home Appliances",
    subCategory: ["Air Quality", "Smart Home"],
    sizes: ["Standard"],
    date: "2024-11-29",
    rating: 4.6,
    bestseller: true,
  },
  {
    id: 16,
    name: "Running Shoes",
    description: "Comfortable and durable running shoes for athletes.",
    price: "89.99",
    image: [img1, img2, img3, img6, img6],
    category: "Footwear",
    subCategory: ["Sports", "Men's Footwear"],
    sizes: ["8", "9", "10", "11"],
    date: "2024-12-07",
    rating: 4.3,
    bestseller: false,
  },
  {
    id: 17,
    name: "Leather Backpack",
    description: "Stylish leather backpack for work or travel.",
    price: "149.99",
    image: [img5, img2, img2, img4, img6],
    category: "Bags",
    subCategory: ["Travel", "Accessories"],
    sizes: ["Standard"],
    date: "2024-12-01",
    rating: 4.5,
    bestseller: true,
  },
  {
    id: 18,
    name: "Electric Toothbrush",
    description: "Smart electric toothbrush with multiple cleaning modes.",
    price: "59.99",
    image: [img1, img2, img3, img4, img5],
    category: "Health",
    subCategory: ["Dental Care", "Smart Devices"],
    sizes: ["One Size"],
    date: "2024-11-27",
    rating: 4.4,
    bestseller: false,
  },
  {
    id: 19,
    name: "Yoga Mat",
    description: "Eco-friendly yoga mat with excellent grip and cushioning.",
    price: "29.99",
    image: [img4, img2, img2, img4, img5],
    category: "Fitness",
    subCategory: ["Exercise", "Accessories"],
    sizes: ["Standard"],
    date: "2024-12-03",
    rating: 4.2,
    bestseller: false,
  },
  {
    id: 20,
    name: "Luxury Watch",
    description: "Elegant luxury watch with a timeless design.",
    price: "999.99",
    image: [img5, img3, img1, img4, img6],
    category: "Accessories",
    subCategory: ["Watches", "Luxury"],
    sizes: ["Standard"],
    date: "2024-12-14",
    rating: 4.8,
    bestseller: true,
  },
];

// export const productData = [
//   {
//     name: "Wireless Earbuds",
//     rating: 2.5,
//     description:
//       "High-quality wireless earbuds with noise cancellation and long battery life.",
//     price: "19,000",
//     former_price: "100,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Smartphone Stand",
//     rating: 4.2,
//     description:
//       "Adjustable and foldable stand for smartphones and tablets, perfect for desk use.",
//     price: "20,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Stainless Steel Water Bottle",
//     rating: 4.8,
//     description:
//       "Eco-friendly stainless steel water bottle with double-wall insulation.",
//     price: "12,000",
//     former_price: "50,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Bluetooth Speaker",
//     rating: 4.6,
//     description:
//       "Compact and portable Bluetooth speaker with deep bass and crisp sound.",
//     price: "39.95",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Gaming Mouse",
//     rating: 4.3,
//     description:
//       "Ergonomic gaming mouse with customizable buttons and RGB lighting.",
//     price: "29,000.99",
//     former_price: "30,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Yoga Mat",
//     rating: 4.7,
//     description:
//       "Non-slip yoga mat with extra cushioning and durability for all practices.",
//     price: "25.0",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "LED Desk Lamp",
//     rating: 4.4,
//     description:
//       "Energy-efficient LED desk lamp with adjustable brightness and color temperature.",
//     price: "18,000.75",
//     former_price: "30,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Noise-Cancelling Headphones",
//     rating: 4.9,
//     description:
//       "Over-ear noise-cancelling headphones with superior sound quality and comfort.",
//     price: "89.99",
//     former_price: "30,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Fitness Tracker",
//     rating: 4.1,
//     description:
//       "Wearable fitness tracker with heart rate monitor, step counter, and sleep tracking.",
//     price: "59.99",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Coffee Maker",
//     rating: 4.5,
//     description:
//       "Programmable coffee maker with a built-in grinder and customizable brew strength.",
//     price: "99.0",
//     former_price: "50,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Wireless Charger",
//     rating: 4.3,
//     description:
//       "Fast wireless charger compatible with all Qi-enabled devices.",
//     price: "19.99",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Laptop Backpack",
//     rating: 4.6,
//     description:
//       "Water-resistant laptop backpack with multiple compartments and USB charging port.",
//     price: "35.0",
//     former_price: "130,000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Digital Alarm Clock",
//     rating: 4.2,
//     description:
//       "LED digital alarm clock with adjustable brightness and dual alarm settings.",
//     price: "17.5",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Smart Thermostat",
//     rating: 4.8,
//     description:
//       "Wi-Fi-enabled smart thermostat with remote control and energy-saving features.",
//     price: "129.99",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Electric Kettle",
//     rating: 4.5,
//     description:
//       "Stainless steel electric kettle with auto shut-off and fast boiling technology.",
//     price: "27.99",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Kitchen Knife Set",
//     rating: 4.7,
//     description:
//       "Professional-grade stainless steel knife set with ergonomic handles.",
//     price: "19000",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Portable Power Bank",
//     rating: 4.4,
//     description:
//       "High-capacity portable power bank with fast charging and dual USB ports.",
//     price: "24.95",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Action Camera",
//     rating: 4.6,
//     description:
//       "Waterproof action camera with 4K recording and wide-angle lens.",
//     price: "89.0",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Cordless Vacuum Cleaner",
//     rating: 4.7,
//     description:
//       "Lightweight and powerful cordless vacuum cleaner with HEPA filtration.",
//     price: "129.99",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
//   {
//     name: "Electric Toothbrush",
//     rating: 4.5,
//     description:
//       "Rechargeable electric toothbrush with multiple cleaning modes.",
//     price: "39.95",
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
//   },
// ];

export const productData = [
  {
    sku: "dj64rb",
    product_number: null,
    name: "Original Yamaha MG10XU",
    product_id: 3,
    merchant_id: null,
    brand_name: "Yamaha",
    category_name: "Electronics",
    category_type: null,
    qty: 6,
    description:
      "<p>Built-in SPX digital effects add polish and professionalism</p>\r\n<p>In order to add that final glue and polish to your mix, the Yamaha MG Series mixing consoles provides you with a comprehensive suite of 24 editable digital effects. Based on Yamaha&rsquo;s acclaimed SPX digital multi-effect processor, the MG Series delivers high-quality reverb, delay, chorus, phaser, flanger, tremolo, and auto-wah, in addition to distortion, pitch effects, and more.</p>\r\n<p>High quality op-amp ensures transparent sound reproduction</p>\r\n<p>Here at Delight musical store we know that few things that will kill tone as quickly as sub-par op-amps. The Yamaha MG Series utilizes new, high-quality MG01 op-amps, ensuring that your mix sounds its best. When designing these op-amps, Yamaha focused on sound quality, rather than prioritizing electrical design and efficiency. Yamaha has always strived to deliver the purest possible signal instead of imparting their &ldquo;signature&rdquo; to your sound, and the MG Series is no exception. You can count on a transparent, natural, and articulate sound when you mix through a MG Series analog mixer.<br /><br /></p>\r\n<p>Product Dimensions &lrm;40 x 13.2 x 36 cm; 3.5 kg</p>\r\n<p>Item model number &lrm;MG10XU</p>\r\n<p>Hardware Interface &lrm;USB</p>\r\n<p>Proficiency Level &lrm;Professional</p>\r\n<p>Power Source &lrm;Corded Electric</p>\r\n<p>Item Weight &lrm;3 kg 500 g</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>",
    url_key: "dj64rb",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "70350.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:09:57.000000Z",
    updated_at: "2024-04-24T16:09:57.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/3/UfzBQL4FKpKC2h4jRTIJ7UEke4lGk8N7j2dTJXNh.jpg",
        azure_url: null,
      },
      {
        local_url:
          "https://saleko.ng/storage/product/3/PZzhyOX2mSr0A3cLxhk0zoh3tKsnmkEp5xFy7NLs.jpg",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "MI893U",
      marketplace_seller_id: 140,
      business_address: "31,olojo drive,Alaba ",
      business_name: "Frank yamaha musical instrument ",
      shop_title: "Frankyamaha",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "alaba international market",
      phone: null,
      state: "LAGOS",
      city: "Lagos",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "lbpyfi",
    product_number: null,
    name: "3in1 Baby Wear with Flannel",
    product_id: 4,
    merchant_id: null,
    brand_name: "Generic",
    category_name: "Babies",
    category_type: null,
    qty: 20,
    description:
      "<p><span style=\"color: #0d0d0d; font-family: S&ouml;hne, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif, 'Helvetica Neue', Arial, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; font-size: 16px; white-space-collapse: preserve;\">Introducing our versatile 3-in-1 Baby Wear with Flannel, the perfect solution for keeping your little one cozy and stylish in any weather. Crafted with care from soft, breathable fabrics, this set offers three essential pieces that can be mixed and matched for endless outfit options.</span></p>\r\n<p>&nbsp;</p>\r\n<p><span style=\"color: #0d0d0d; font-family: S&ouml;hne, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif, 'Helvetica Neue', Arial, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; font-size: 16px; white-space-collapse: preserve;\">This 3-in-1 Baby Wear with Flannel set is perfect for busy parents on the go, offering convenience, comfort, and style in one package. Whether you're running errands, attending a playdate, or simply lounging at home, this versatile set has you covered for all occasions. Treat your little one to the ultimate in cozy comfort with our 3-in-1 Baby Wear with Flannel set to</span></p>",
    url_key: "lbpyfi",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "9900.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:20:55.000000Z",
    updated_at: "2024-04-24T16:20:55.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/4/HqXFnf5zlcnHdEmyq3j1b8BhJgvaGxPWd9kGkmDH.jpg",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "ML594Y",
      marketplace_seller_id: 57,
      business_address: "5, Moshalashi str., Docemo",
      business_name: "Gerannelne baby world enterprise",
      shop_title: "gerannelne baby",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "apogbon",
      phone: null,
      state: "LAGOS",
      city: "Lagos Island",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "imzpda",
    product_number: null,
    name: "INFERTINO BABY CARRIER",
    product_id: 5,
    merchant_id: null,
    brand_name: "Generic",
    category_name: "Babies",
    category_type: null,
    qty: 30,
    description:
      "<p><span style=\"color: #0d0d0d; font-family: S&ouml;hne, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif, 'Helvetica Neue', Arial, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; font-size: 16px; white-space-collapse: preserve;\">The Infertino Baby Carrier offers both style and functionality, providing a comfortable and secure way to carry your little one while keeping your hands free. Crafted with high-quality materials and thoughtful design, this carrier ensures both parent and baby are comfortable during use.</span></p>\r\n<p>&nbsp;</p>\r\n<p><span style=\"color: #0d0d0d; font-family: S&ouml;hne, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif, 'Helvetica Neue', Arial, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; font-size: 16px; white-space-collapse: preserve;\">Designed for versatility, the Infertino Baby Carrier allows for multiple carrying positions, including front-facing, inward-facing, and back-carrying options, catering to the evolving needs of both parent and child. Its adjustable straps and padded lumbar support ensure proper weight distribution, reducing strain on the wearer's back and shoulders.</span></p>\r\n<p>&nbsp;</p>\r\n<p><span style=\"color: #0d0d0d; font-family: S&ouml;hne, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif, 'Helvetica Neue', Arial, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; font-size: 16px; white-space-collapse: preserve;\">Safety is paramount with the Infertino Baby Carrier, featuring sturdy buckles and straps to keep your baby snug and secure at all times. The carrier also includes breathable fabric and ventilation panels to keep both parent and baby cool and comfortable, even during extended wear.</span></p>",
    url_key: "imzpda",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "30800.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:26:54.000000Z",
    updated_at: "2024-04-24T16:26:54.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/5/s0yPgu6IhqpSLEXe83kmpApoEuXEe5ohF1eAAY8W.jpg",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "ML594Y",
      marketplace_seller_id: 57,
      business_address: "5, Moshalashi str., Docemo",
      business_name: "Gerannelne baby world enterprise",
      shop_title: "gerannelne baby",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "apogbon",
      phone: null,
      state: "LAGOS",
      city: "Lagos Island",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "z7l81g",
    product_number: null,
    name: "Original Yamaha MG16XU",
    product_id: 6,
    merchant_id: null,
    brand_name: "Yamaha",
    category_name: "Electronics",
    category_type: null,
    qty: 8,
    description:
      '<p style="box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: \'Helvetica Neue\', -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Fira Sans\', \'Droid Sans\', sans-serif; font-size: 15px;">High quality op-amp ensures transparent sound reproduction</p>\r\n<p style="box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: \'Helvetica Neue\', -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Fira Sans\', \'Droid Sans\', sans-serif; font-size: 15px;">Here at Gopandy, we know that few things will kill tone as quickly as sub-par op-amps. The Yamaha MG Series utilizes new, high-quality MG01 op-amps, ensuring that your mix sounds its best. When designing these op-amps, Yamaha focused on sound quality, rather than prioritizing electrical design and efficiency.</p>\r\n<p style="box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: \'Helvetica Neue\', -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Fira Sans\', \'Droid Sans\', sans-serif; font-size: 15px;">Yamaha has always strived to deliver the purest possible signal instead of imparting their &ldquo;signature&rdquo; to your sound, and the MG Series is no exception. You can count on a transparent, natural, and articulate sound when you mix through a MG Series analog mixer.</p>\r\n<p style="box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: \'Helvetica Neue\', -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Fira Sans\', \'Droid Sans\', sans-serif; font-size: 15px;">What\'s in the box<br style="box-sizing: border-box;" />Yamaha MG16XU 16-channel Mixer with USB and FX<br style="box-sizing: border-box;" />Power Cable<br style="box-sizing: border-box;" />Features<br style="box-sizing: border-box;" />Type: Analog<br style="box-sizing: border-box;" />Channels: 16<br style="box-sizing: border-box;" />Computer Connectivity: USB (2 x 2)<br style="box-sizing: border-box;" />Faders: 16 Faders<br style="box-sizing: border-box;" />Inputs - Mic Preamps: 8 x XLR/TRS Combo, 2 x XLR, 4 x TRS<br style="box-sizing: border-box;" />Phantom Power: 12<br style="box-sizing: border-box;" />Inputs - Line: 4 x TRS<br style="box-sizing: border-box;" />Inputs - Other: 2 x RCA (Stereo)<br style="box-sizing: border-box;" />Outputs - Main: 2 x XLR, 4 x TRS<br style="box-sizing: border-box;" />Outputs - Direct: 4 x TRS<br style="box-sizing: border-box;" />Outputs - Other: 1 x TRS (Footswitch)<br style="box-sizing: border-box;" />Aux Sends: 1 x Pre, 1 x Post/Pre, 2 x Post<br style="box-sizing: border-box;" />Send/Return I/O: 4 x TRS (Send)<br style="box-sizing: border-box;" />Busses/Groups: 4 x Groups<br style="box-sizing: border-box;" />Headphones: 1 x 1/4"<br style="box-sizing: border-box;" />USB: 1 x Type B<br style="box-sizing: border-box;" />EQ Bands: 3-Band, Sweepable Mid<br style="box-sizing: border-box;" />Effects: Yes<br style="box-sizing: border-box;" />Software: Cubase AI DAW software (download)<br style="box-sizing: border-box;" />Rackmountable: Yes<br style="box-sizing: border-box;" />Height: 5.1"<br style="box-sizing: border-box;" />Width: 17.5"<br style="box-sizing: border-box;" />Depth: 19.7"<br style="box-sizing: border-box;" />Weight: 14.6 lbs.<br style="box-sizing: border-box;" />Manufacturer Part Number: MG16XU</p>',
    url_key: "z7l81g",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "231000.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:31:03.000000Z",
    updated_at: "2024-04-24T16:31:03.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/6/nuXFtXzfcaudGhWvAhKcaAlcp4LTuzQbEzMAzfEI.jpg",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "MI893U",
      marketplace_seller_id: 140,
      business_address: "31,olojo drive,Alaba ",
      business_name: "Frank yamaha musical instrument ",
      shop_title: "Frankyamaha",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "alaba international market",
      phone: null,
      state: "LAGOS",
      city: "Lagos",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "uqt8wl",
    product_number: null,
    name: "BABY DISCOVERY CARRIER",
    product_id: 7,
    merchant_id: null,
    brand_name: "Generic",
    category_name: "Babies",
    category_type: null,
    qty: 30,
    description:
      "<p><span style=\"color: #313133; font-family: Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;\">The baby carrier provides extra comfortable lining and adjustable padded straps for the comfort of both mommy and baby. The carrier features an exclusive cuddle pocket to soothe and comfort baby, as well as a washable snap-on spit-up cloth, and vented side mesh panels.&nbsp;</span></p>",
    url_key: "uqt8wl",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "11000.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:32:09.000000Z",
    updated_at: "2024-04-24T16:32:09.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/7/H8Jq5twGxoq4UnyG1mHLNhWiZkNcpx2pKMqPHKj4.png",
        azure_url: null,
      },
      {
        local_url:
          "https://saleko.ng/storage/product/7/ZOGfX62fLiVNXXqTrdoPiGyZgIiUVrtifQ7oFN07.png",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "ML594Y",
      marketplace_seller_id: 57,
      business_address: "5, Moshalashi str., Docemo",
      business_name: "Gerannelne baby world enterprise",
      shop_title: "gerannelne baby",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "apogbon",
      phone: null,
      state: "LAGOS",
      city: "Lagos Island",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "oe3rdk",
    product_number: null,
    name: "Sounds prince PA system 15 inches ",
    product_id: 8,
    merchant_id: null,
    brand_name: "Sound Prince",
    category_name: "Electronics",
    category_type: null,
    qty: 10,
    description:
      "<p style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif; font-size: 15px;\">Sound prince public address system 15 inches&nbsp;</p>\r\n<p style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif; font-size: 15px;\">With big magnet speaker ,big cone&nbsp;</p>\r\n<p style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif; font-size: 15px;\">Come with five band equalizer at the front panel&nbsp;</p>\r\n<p style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif; font-size: 15px;\">Also with 12volt machine battery&nbsp; (rechargeable)</p>\r\n<p style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif; font-size: 15px;\">Has USB/SD/FM/BT/Record&nbsp; two wire mic jack and one guitar jack&nbsp;</p>\r\n<p style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif; font-size: 15px;\">5000watts&nbsp;</p>\r\n<p style=\"box-sizing: border-box; margin: 0px; padding: 0px;\"><span style=\"color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif; font-size: 15px;\">Soundprince 1560 trolley speaker comes with two wireless microphones that can cover up to 100meters. It plays music with USB, Bluetooth, or memory card . It has bass, treble, and equalizer for music sound control ,it also has mic volume ,mic echo and guitar volume for microphones and guitar control.<br style=\"box-sizing: border-box;\" />You can connect to keyboard and guitar. It has Bluetooth which&nbsp; enables you play music from your&nbsp;<em class=\"Highlight ht730d699c-b650-4ca1-a89d-04b0b14aa52b\" style=\"box-sizing: border-box;\">phone</em>&nbsp;,also has radio which can be selected through the mode<br style=\"box-sizing: border-box;\" />Designed for teaching ,evangelism, outdoors and indoors party with other public activities.<br /><br />weight - </span><span style=\"color: #8f8f8f; font-family: 'Helvetica Neue', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', sans-serif;\"><span style=\"font-size: 15px;\">0.90 kg</span></span></p>\r\n<p>color - Black</p>",
    url_key: "oe3rdk",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "159500.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:41:12.000000Z",
    updated_at: "2024-04-24T16:41:12.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/8/0XTtpCCHLAYdNnva5SY4IHMH1DNcN1atyisIoQVm.jpg",
        azure_url: null,
      },
      {
        local_url:
          "https://saleko.ng/storage/product/8/b6UskCckzHPnnwQuJNww6mKMv6kRK7SIryzzOavJ.jpg",
        azure_url: null,
      },
      {
        local_url:
          "https://saleko.ng/storage/product/8/QcojREptB86FnMPAwBvPc902KVUev0xFJSvnSWyu.jpg",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "MI893U",
      marketplace_seller_id: 140,
      business_address: "31,olojo drive,Alaba ",
      business_name: "Frank yamaha musical instrument ",
      shop_title: "Frankyamaha",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "alaba international market",
      phone: null,
      state: "LAGOS",
      city: "Lagos",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "aguqbm",
    product_number: null,
    name: "Boyfriend Jeans trousers (Ages 10yrs-15yrs)",
    product_id: 9,
    merchant_id: null,
    brand_name: "Generic",
    category_name: "Fashion",
    category_type: null,
    qty: 100,
    description:
      "<p>● urban</p>\r\n<p>●&nbsp;Stylish&nbsp;</p>\r\n<p>● Original</p>\r\n<p>● Durable</p>",
    url_key: "aguqbm",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "10500.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:41:49.000000Z",
    updated_at: "2024-04-24T16:41:50.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/9/tnFnYShmy4CCgmLzO5AAhez8gz3rfhGlUtcNi7Qs.jpg",
        azure_url: null,
      },
    ],
    variants: [
      {
        id: 10,
        sku: "aguqbm-variant-1",
        name: "Boyfriend Jeans trousers (Ages 10yrs-15yrs) (Size: 32-40 | Color: blue)",
        price: "10500.0000",
        special_price: null,
        special_price_from: null,
        special_price_to: null,
        color: "blue",
        size: "32-40",
        qty: 100,
      },
    ],
    seller: {
      merchant_id: "ME322T",
      marketplace_seller_id: 67,
      business_address: "Anny Plaza, block 2 Martins str",
      business_name: "Ikonyetubeventures",
      shop_title: "Ikonyetubeventures",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "balogun market",
      phone: null,
      state: "LAGOS",
      city: "lagos ",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "wlpcmv",
    product_number: null,
    name: "FISHER PRICE BAG",
    product_id: 11,
    merchant_id: null,
    brand_name: "Generic",
    category_name: "Babies",
    category_type: null,
    qty: 20,
    description:
      "<p><span style=\"color: #313133; font-family: Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;\">Fisher-price Mother backpack.&nbsp;</span><br style=\"box-sizing: border-box; color: #313133; font-family: Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;\" /><span style=\"color: #313133; font-family: Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;\">This backpack is for new generation mommies. It is divided from the inside to carry all the baby's purposes. The waterproof pouch accommodates your purposes and your child's purposes. Can be carried easily on the back or handset have pockets of napkins, money, and phone.</span></p>",
    url_key: "wlpcmv",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "16500.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:43:52.000000Z",
    updated_at: "2024-04-24T16:43:52.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/11/ncbkBuj8PZZzsCtTSSglpmJuaaX2oXs5wqw1YqyZ.png",
        azure_url: null,
      },
      {
        local_url:
          "https://saleko.ng/storage/product/11/VZ0Bsa7YD2aYGKQgYAqpJjv9jYNlWxr4jflEDKmx.png",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "ML594Y",
      marketplace_seller_id: 57,
      business_address: "5, Moshalashi str., Docemo",
      business_name: "Gerannelne baby world enterprise",
      shop_title: "gerannelne baby",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "apogbon",
      phone: null,
      state: "LAGOS",
      city: "Lagos Island",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "msvfkg",
    product_number: null,
    name: "CHICCO BACKING BAG",
    product_id: 12,
    merchant_id: null,
    brand_name: "Generic",
    category_name: "Babies",
    category_type: null,
    qty: 20,
    description:
      "<p><span style=\"color: #313133; font-family: Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;\">This mother bag is divided from the inside to carry all the baby's purposes. Waterproof pouchaccommodate your purposes and your child's purposes. Can be carried easily on the back or hands. It has pockets for napkins, money, phone etc.</span></p>",
    url_key: "msvfkg",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "16500.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:50:00.000000Z",
    updated_at: "2024-04-24T16:50:00.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/12/2sgrIVYr7GbSIgzvjcNp74CzDGNNtf6TICpYNuKH.png",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "ML594Y",
      marketplace_seller_id: 57,
      business_address: "5, Moshalashi str., Docemo",
      business_name: "Gerannelne baby world enterprise",
      shop_title: "gerannelne baby",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "apogbon",
      phone: null,
      state: "LAGOS",
      city: "Lagos Island",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
  {
    sku: "yb4k61",
    product_number: null,
    name: "Fendi clothing gifts set 4pcs",
    product_id: 13,
    merchant_id: null,
    brand_name: "Fendi",
    category_name: "Babies",
    category_type: null,
    qty: 10,
    description:
      "<p style=\"border: 0px solid #e3e3e3; box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(69,89,164,.5); --tw-ring-offset-shadow: 0 0 transparent; --tw-ring-shadow: 0 0 transparent; --tw-shadow: 0 0 transparent; --tw-shadow-colored: 0 0 transparent; margin: 0px 0px 1.25em; color: #0d0d0d; font-family: S&ouml;hne, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif, 'Helvetica Neue', Arial, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; font-size: 16px; white-space-collapse: preserve;\">The Fendi Clothing Gift Set 4pc embodies luxury and sophistication, making it the perfect ensemble for the stylish little one in your life. Crafted with meticulous attention to detail and using only the finest materials, each piece exudes the iconic Fendi charm and flair.</p>\r\n<p style=\"border: 0px solid #e3e3e3; box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(69,89,164,.5); --tw-ring-offset-shadow: 0 0 transparent; --tw-ring-shadow: 0 0 transparent; --tw-shadow: 0 0 transparent; --tw-shadow-colored: 0 0 transparent; margin: 1.25em 0px; color: #0d0d0d; font-family: S&ouml;hne, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif, 'Helvetica Neue', Arial, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; font-size: 16px; white-space-collapse: preserve;\">This exquisite gift set includes four essential pieces designed to elevate any baby's wardrobe.</p>",
    url_key: "yb4k61",
    new: 1,
    featured: 1,
    status: 1,
    thumbnail: null,
    price: "14300.0000",
    special_price: "0.0000",
    special_price_from: null,
    special_price_to: null,
    percentage_discount: 0,
    promo_count_down: false,
    weight: "0.0000",
    color: 0,
    color_label: null,
    size: 0,
    size_label: null,
    created_at: "2024-04-24T16:57:36.000000Z",
    updated_at: "2024-04-24T16:57:36.000000Z",
    image_urls: [
      {
        local_url:
          "https://saleko.ng/storage/product/13/jfZHknySWlcZ4bmTLBS1DAj6RhZb8GGFKuYtBUFc.jpg",
        azure_url: null,
      },
    ],
    variants: [],
    seller: {
      merchant_id: "ML594Y",
      marketplace_seller_id: 57,
      business_address: "5, Moshalashi str., Docemo",
      business_name: "Gerannelne baby world enterprise",
      shop_title: "gerannelne baby",
      banner:
        "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      logo: "https://saleko.ng/themes/msmarvel/assets/images/store-banner.png",
      market_name: "apogbon",
      phone: null,
      state: "LAGOS",
      city: "Lagos Island",
      country: null,
      twitter: null,
      facebook: null,
      youtube: null,
      instagram: null,
      skype: null,
      linked_in: null,
    },
  },
];

export const bestSellerData = [
  {
    id: 1,
    name: "Wireless Earbuds",
    rating: 2.5,
    description:
      "High-quality wireless earbuds with noise cancellation and long battery life.",
    price: "19,000",
    former_price: "100,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-31T23:59:59",
  },
  {
    id: 2,
    name: "Smartphone Stand",
    rating: 4.2,
    description:
      "Adjustable and foldable stand for smartphones and tablets, perfect for desk use.",
    price: "20,000",
    former_price: "80,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-29T23:59:59",
  },
  {
    id: 3,
    name: "Stainless Steel Water Bottle",
    rating: 4.8,
    description:
      "Eco-friendly stainless steel water bottle with double-wall insulation.",
    price: "12,000",
    former_price: "50,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-27T23:59:59",
  },
  {
    id: 4,
    name: "Bluetooth Speaker",
    rating: 4.6,
    description:
      "Compact and portable Bluetooth speaker with deep bass and crisp sound.",
    price: "39,000.95",
    former_price: "40,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-25T23:59:59",
  },
  {
    id: 5,
    name: "Gaming Mouse",
    rating: 4.3,
    description:
      "Ergonomic gaming mouse with customizable buttons and RGB lighting.",
    price: "29,000.99",
    former_price: "30,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-23T23:59:59",
  },
  {
    id: 6,
    name: "Yoga Mat",
    rating: 4.7,
    description:
      "Non-slip yoga mat with extra cushioning and durability for all practices.",
    price: "2,500.0",
    former_price: "10,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-21T23:59:59",
  },
  {
    id: 7,
    name: "LED Desk Lamp",
    rating: 4.4,
    description:
      "Energy-efficient LED desk lamp with adjustable brightness and color temperature.",
    price: "18,000.75",
    former_price: "30,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-19T23:59:59",
  },
  {
    id: 8,
    name: "Noise-Cancelling Headphones",
    rating: 4.9,
    description:
      "Over-ear noise-cancelling headphones with superior sound quality and comfort.",
    price: "89.99",
    former_price: "30,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-17T23:59:59",
  },
  {
    id: 9,
    name: "Fitness Tracker",
    rating: 4.1,
    description:
      "Wearable fitness tracker with heart rate monitor, step counter, and sleep tracking.",
    price: "59,000.99",
    former_price: "100,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-15T23:59:59",
  },
  {
    id: 10,
    name: "Coffee Maker",
    rating: 4.5,
    description:
      "Programmable coffee maker with a built-in grinder and customizable brew strength.",
    price: "99,000.0",
    former_price: "150,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-15T23:59:59",
  },
  {
    id: 11,
    name: "Wireless Charger",
    rating: 4.3,
    description:
      "Fast wireless charger compatible with all Qi-enabled devices.",
    price: "15,000.99",
    former_price: "20,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-13T23:59:59",
  },
  {
    id: 12,
    name: "Laptop Backpack",
    rating: 4.6,
    description:
      "Water-resistant laptop backpack with multiple compartments and USB charging port.",
    price: "35,000.0",
    former_price: "130,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-11T23:59:59",
  },
  {
    id: 13,
    name: "Digital Alarm Clock",
    rating: 4.2,
    description:
      "LED digital alarm clock with adjustable brightness and dual alarm settings.",
    price: "17,000.5",
    former_price: "20,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-09T23:59:59",
  },
  {
    id: 14,
    name: "Smart Thermostat",
    rating: 4.8,
    description:
      "Wi-Fi-enabled smart thermostat with remote control and energy-saving features.",
    price: "129,000.99",
    former_price: "200,000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnXvFGX8_ADclqgSMV4-j4bPGfUVQN-Ipjp7l7cDbaxoqIoXc3lp552Tg&s",
    targetDate: "2025-01-07T23:59:59",
  },
];

export const storeData = [
  {
    name: "Mike stores",
    orders: "10,000",
  },
  {
    name: "Book stores",
    orders: "100",
  },
  {
    name: "Cookie stores",
    orders: "6,000",
  },
  {
    name: "Jersey stores",
    orders: "10",
  },
  {
    name: "Milk stores",
    orders: "2,000",
  },
  {
    name: "Mimi stores",
    orders: "10,000",
  },
  {
    name: "Caleb stores",
    orders: "10,000",
  },
  {
    name: "Matthew stores",
    orders: "10,000",
  },
  {
    name: "kofo stores",
    orders: "10,000",
  },
];

export const features = [
  {
    feature:
      "Durable leather is easily cleanable so you can keep your look fresh.",
  },
  {
    feature:
      "Water-repellent finish and internal membrane help keep your feet dry.",
  },
  { feature: "Toe piece with star pattern adds durability." },
  { feature: "Synthetic insulation helps keep you warm." },
  {
    feature:
      "Originally designed for performance hoops, the Air unit delivers lightweight cushioning.",
  },
  {
    feature:
      "Plush tongue wraps over the ankle to help keep out the moisture and cold.",
  },
  {
    feature:
      "Rubber outsole with aggressive traction pattern adds durable grip.",
  },
  {
    feature:
      "Durable leather is easily cleanable so you can keep your look fresh.",
  },
];

export const productReviews = [
  {
    title: "Amazing Product!",
    rating: 5,
    review:
      "This product exceeded my expectations. The quality is top-notch, and it works perfectly!",
    date: "2024-12-01",
    person: "Alice Johnson",
  },
  {
    title: "Good Value for Money",
    rating: 4,
    review:
      "The product is worth the price. A few minor issues, but overall, I'm satisfied.",
    date: "2024-11-25",
    person: "Michael Smith",
  },
  {
    title: "Not as Expected",
    rating: 2,
    review:
      "The product didn't match the description. Disappointed with the quality.",
    date: "2024-11-20",
    person: "Karen Williams",
  },
  {
    title: "Highly Recommend!",
    rating: 5,
    review:
      "Fantastic product! I would definitely recommend this to my friends and family.",
    date: "2024-11-18",
    person: "James Brown",
  },
  {
    title: "Decent Purchase",
    rating: 3,
    review: "It works okay but has some flaws. Could be improved.",
    date: "2024-11-15",
    person: "Patricia Garcia",
  },
  {
    title: "Terrible Experience",
    rating: 1,
    review:
      "This was a waste of money. Poor build quality and bad customer service.",
    date: "2024-11-10",
    person: "Robert Martinez",
  },
  {
    title: "Satisfactory",
    rating: 4,
    review:
      "The product does its job well. Delivery was quick, and the packaging was good.",
    date: "2024-11-05",
    person: "Linda Anderson",
  },
  {
    title: "Exceptional Quality",
    rating: 5,
    review:
      "The quality is outstanding! I've been using it for a week, and it's perfect.",
    date: "2024-11-01",
    person: "David Thomas",
  },
  {
    title: "Wouldn't Buy Again",
    rating: 2,
    review:
      "The product broke within a few days of use. Not satisfied with the durability.",
    date: "2024-10-28",
    person: "Barbara Lee",
  },
  {
    title: "Best Purchase Ever",
    rating: 5,
    review: "Absolutely love this! It’s the best thing I’ve bought this year.",
    date: "2024-10-20",
    person: "John Harris",
  },
];

export const storelistdata = [
  {
    id: 1,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 2,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 3,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 4,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
  {
    id: 5,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 6,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 7,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 8,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
  {
    id: 9,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 10,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 11,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 12,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
  {
    id: 13,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 14,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 15,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 16,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
  {
    id: 17,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 18,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 19,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 20,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
  {
    id: 21,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 22,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 23,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 24,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
  {
    id: 25,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 26,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 27,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 28,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
  {
    id: 29,
    store_name: "Silzal Store",
    store_market: "Mushin Market",
    category: "Electronics",
  },
  {
    id: 30,
    store_name: "Mimiejae Store",
    store_market: "Alaba International Market",
    category: "Electronics",
  },
  {
    id: 31,
    store_name: "Jatto Boutiques",
    store_market: "Idumota Market",
    category: "Electronics",
  },
  {
    id: 32,
    store_name: "Idumota Market",
    store_market: "Alaba Market",
    category: "Electronics",
  },
];
