export const MarketPlace = [
  { name: "All Markets" },
  { name: "Agboju" },
  { name: "Agege Market" },
  { name: "Ajah Market" },
  { name: "Akodu Market, Epe" },
  { name: "Alaba International Market" },
  { name: "Apogbon" },
  { name: "Arena Market" },
  { name: "Aspamda" },
  { name: "Balogun Market" },
  { name: "Computer Village" },
  { name: "Daleko" },
  { name: "Ebuta-ero" },
  { name: "Idumagbo" },
  { name: "Idumota" },
  { name: "Ikotun" },
  { name: "Jankara" },
  { name: "Mile 12" },
  { name: "Mushin Market" },
  { name: "Odunade" },
  { name: "Ojuwoye" },
  { name: "Oke-arin" },
  { name: "Oshodi" },
  { name: "Oyingbo" },
  { name: "Tejuosho/yaba" },
  { name: "Tradefair" },
  { name: "Other Markets" },
];
